# Ruff configuration file
# See: https://docs.astral.sh/ruff/configuration

[tool.ruff]
# Same as Black
line-length = 88
indent-width = 4

[tool.ruff.lint]
unfixable = ["F401"]
ignore = ["ERA001"]

[tool.ruff.format]
line-ending = "lf"

# Like Black, use double quotes for strings
quote-style = "double"

# Like Black, indent with spaces, rather than tabs
indent-style = "space"

# Like Black, respect magic trailing commas
skip-magic-trailing-comma = false
